# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: yvideo frontend CI

on:
  push:
    branches: [ develop, build ]
  pull_request:
    branches: [ develop, build ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      with: y-video-back-end
      github_token: ${{ secrets.YVIDEO_ACCESS_TOKEN }}
      workflow_file_name: clojure.yml
      ref: development
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # - run: npm install
    # - run: npm test
    # - run: npm build
    #  yvideo_repo_token
    #  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
    # go to secrets to save this token for access
