# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: yvideo frontend CI

on:
  push:
    branches: [ develop, build ]
  pull_request:
    branches: [ develop, build ]
  repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: PING - Dispatch initiating repository event
        if: github.event.action != 'pong'
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/youthrich40/y-video-back-end/dispatches \
            -d '{"event_type":"ping"}'

        # run: |
        #   curl -X POST https://api.github.com/repos/youthrich40/y-video-back-end/dispatches \
        #   -H 'Accept: application/vnd.github.everest-preview+json' \
        #   -u ${{ secrets.YVIDEO_ACCESS_TOKEN }} \
        #   --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

    strategy:
      matrix:
        node-version: [14.x]

    # steps:
    #   run: |
    #     curl -X POST https://api.github.com/repos/youthrich40/y-video-back-end/dispatches \
    #     -H 'Accept: application/vnd.github.everest-preview+json' \
    #     -u ${{ secrets.ACCESS_TOKEN }} \
    #     --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
    # - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'

    # - uses: convictional/trigger-workflow-and-wait@v1.3.0
    #   with:
    #     owner: youthrich40
    #     repo: y-video-back-end
    #     github_token: ${{ secrets.YVIDEO_ACCESS_TOKEN }}
    #     workflow_file_name: clojure.yml
    #     ref: development
    # - run: npm install
    # - run: npm test
    # - run: npm build
    #  yvideo_repo_token
    #  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
    # go to secrets to save this token for access